### PR TITLE
Fixes #1221 missing transformInfo on sceneItem

### LINKED ISSUE #1221: sceneItem.transformInfo throw error
sceneItem.transformInfo;

Error: Function 'GetTransformInfo' not found in class 'SceneItem'.

### PR DESCRIPTION
**Pull request by avoitenko-logitech**
### Description
Implemented getter and setter for sceneItem.transformInfo

### Motivation and Context
https://github.com/stream-labs/obs-studio-node/issues/1221

### How Has This Been Tested?
Unit tests were added

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by eugen15 — APPROVED** [review]

File: obs-studio-client/source/sceneitem.cpp [hunk 1]
```diff
@@ -745,59 +745,62 @@ Napi::Value osn::SceneItem::GetTransformInfo(const Napi::CallbackInfo &info)
...
-	//ASSERT_GET_OBJECT_FIELD(tf_info_object, "boundsAlignment", tf_info.bounds_alignment);
-	//ASSERT_GET_OBJECT_FIELD(tf_info_object, "bounds", tf_info.bounds);
+	auto conn = GetConnection(info);
+	if (!conn) {
+		return;
+	}
 
-	//handle.transform_info(tf_info);
+	const auto b = conn->call("SceneItem", "SetTransformInfo",
+				  std::vector<ipc::value>{
```
Comment (summeroff) [inline obs-studio-client/source/sceneitem.cpp]: Maybe worth moving vector setup outside of a function call?
It will be easier to debug if debugger has more code lines to point to.

Comment (avoitenko-logitech) [reply obs-studio-client/source/sceneitem.cpp]: Done

**Review by summeroff — APPROVED** [review]
